### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by k3x** [herrherrmann/awesome-multiplayer-games#13]
call of duty 1&2
Overcooked 2
Tesseract ( http://tesseract.gg/ )
Keep Talking an nobody explodes

**Comment by herrherrmann** [comment]
Thank you!

I’ve added Overcooked 2 and  Keep Talking and nobody explodes now! CoD 1 & 2 seem a bit too similar to Call of Duty 4 (which is already on the list) to me. And Tesseract hasn’t fully convinced me, even after watching the trailer. :P
